# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VectorRubber
                                 A QGIS plugin
 This plugin allows removing features from multiple vector layers at once.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-24
        copyright            : (C) 2026 by Natalia Budzińska
        email                : nataliabudzinska348@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load VectorRubber class from file VectorRubber.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .vector_rubber import VectorRubber
    return VectorRubber(iface)
