# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VectorRubberDockWidget
                                 A QGIS plugin
 This plugin allows removing features from multiple vector layers at once.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-24
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Natalia Budzińska
        email                : nataliabudzinska348@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal

from qgis.core import *
import qgis.utils
from qgis.utils import iface 
from PyQt5.QtWidgets import QListWidgetItem
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QAction
from PyQt5.QtWidgets import QAbstractItemView

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'vector_rubber_dockwidget_base.ui'))

class VectorRubberDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        super(VectorRubberDockWidget, self).__init__(parent)
        self.setupUi(self)

        canvas = iface.mapCanvas()
        self.fill_listWidget_with_layers()

        self.pb_select.clicked.connect(self.select_layers)
        self.pb_uncheck.clicked.connect(self.uncheck_layers)

        self.pb_confirm_layers.clicked.connect(lambda : self.enable_widget(self.pb_delete_feats))
        self.pb_delete_feats.clicked.connect(lambda : self.enable_widget(self.pb_save))

    def enable_widget(self, widget):
        widget.setEnabled(True)

    def fill_listWidget_with_layers(self):
        self.list_layers.clear()

        for layer in QgsProject.instance().mapLayers().values():
            if isinstance(layer, QgsVectorLayer):

                item = QListWidgetItem(layer.name())
                item.setFlags(item.flags() | Qt.ItemIsUserCheckable)
                item.setCheckState(Qt.Unchecked)
                self.list_layers.addItem(item)
            self.list_layers.setSelectionMode(QAbstractItemView.ExtendedSelection)


    def select_layers(self):
        for x in range(self.list_layers.count()):
            item = self.list_layers.item(x)
            if item.text()== 'fid':
                item.setCheckState(Qt.Unchecked)
            else:
                item.setCheckState(Qt.Checked)
            
    def uncheck_layers(self):
        for x in range(self.list_layers.count()):
            item = self.list_layers.item(x)
            item.setCheckState(Qt.Unchecked) 

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
